refactor: add trigger and imports to queue sqs

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -57,8 +57,36 @@ jobs:
 
       - name: Import existing AWS resources
         run: |
-          export QUEUE_NAME="${{ env.PROJECT_NAME }}-queue"
-          export AWS_REGION="${{ env.AWS_REGION }}"
+          # Configurações dinâmicas
+          QUEUE_NAME="${{ env.PROJECT_NAME }}-queue"
+          AWS_REGION="${{ env.AWS_REGION }}"
+          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
+
+          # Importar a fila SQS se existir
+          QUEUE_URL=$(aws sqs get-queue-url --queue-name "$QUEUE_NAME" --region "$AWS_REGION" --query 'QueueUrl' --output text 2>/dev/null)
+          if [ -n "$QUEUE_URL" ]; then
+            terraform import aws_sqs_queue.skeleton_pub_queue "$QUEUE_URL"
+          else
+            echo "Queue $QUEUE_NAME does not exist"
+          fi
+
+          # Importar permissão de invocação da Lambda pela SQS
+          terraform import aws_lambda_permission.allow_sqs_invoke "${{ env.PROJECT_NAME }}/AllowExecutionFromSQS" || echo "Permission already managed"
+
+          # Importar Event Source Mapping se já existir
+          MAPPING_UUID=$(aws lambda list-event-source-mappings \
+            --function-name "${{ env.PROJECT_NAME }}" \
+            --event-source "arn:aws:sqs:${AWS_REGION}:${ACCOUNT_ID}:${QUEUE_NAME}" \
+            --region "$AWS_REGION" \
+            --query 'EventSourceMappings[0].UUID' \
+            --output text 2>/dev/null)
+
+          if [ "$MAPPING_UUID" != "None" ] && [ -n "$MAPPING_UUID" ]; then
+            terraform import aws_lambda_event_source_mapping.from_sqs "$MAPPING_UUID"
+          else
+            echo "Event Source Mapping not found for $QUEUE_NAME"
+          fi
+
           terraform import aws_s3_bucket.lambda_code_bucket meu-unico-bucket-s3 || echo "Bucket já gerenciado"
           terraform import aws_iam_role.lambda_execution_role ${{ env.PROJECT_NAME }}_execution_role || echo "Role já gerenciada"
           terraform import aws_cloudwatch_log_group.lambda_log_group "/aws/lambda/${{ env.PROJECT_NAME }}" || echo "Log group já gerenciado"
