refactor: add import sqs queue if exists

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -7,6 +7,8 @@ on:
 jobs:
   deploy:
     runs-on: ubuntu-latest
+    env:
+      AWS_REGION: us-east-1
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
@@ -60,39 +62,46 @@ jobs:
           terraform import aws_s3_bucket.lambda_code_bucket meu-unico-bucket-s3 || echo "Bucket already managed"
           terraform import aws_iam_role.lambda_execution_role ${{ env.PROJECT_NAME }}_execution_role || echo "Role already managed"
           terraform import aws_cloudwatch_log_group.lambda_log_group "/aws/lambda/${{ env.PROJECT_NAME }}" || echo "Log group already managed"
-          terraform import aws_lambda_function.my_lambda_function ${{ env.PROJECT_NAME }}
+          terraform import aws_lambda_function.my_lambda_function ${{ env.PROJECT_NAME }} || echo "Lambda function already managed"
+
           QUEUE_URL=$(aws sqs get-queue-url --queue-name "$QUEUE_NAME" --region "$AWS_REGION" --query 'QueueUrl' --output text 2>/dev/null)
           if [ -n "$QUEUE_URL" ]; then
             echo "Importando a fila SQS existente: $QUEUE_URL"
-            terraform import aws_sqs_queue.my_queue "$QUEUE_URL"
+            terraform import aws_sqs_queue.my_queue "$QUEUE_URL" || echo "Queue already managed"
           else
             echo "Fila '$QUEUE_NAME' não encontrada na região '$AWS_REGION'."
           fi
-          terraform import aws_lambda_permission.allow_sqs_invoke ${{ env.PROJECT_NAME }}/AllowExecutionFromSQS || echo "Permission already managed"
+
+          # Importar permissão Lambda se existir
+          PERMISSION_EXISTS=$(aws lambda get-policy --function-name ${{ env.PROJECT_NAME }} --region "$AWS_REGION" --query 'Policy' --output text 2>/dev/null)
+          if [ -n "$PERMISSION_EXISTS" ]; then
+            terraform import aws_lambda_permission.allow_sqs_invoke "${{ env.PROJECT_NAME }}/AllowExecutionFromSQS" || echo "Permission already managed"
+          else
+            echo "Lambda permission not found"
+          fi
+
           # Importar Event Source Mapping se já existir
           MAPPING_UUID=$(aws lambda list-event-source-mappings \
             --function-name ${{ env.PROJECT_NAME }} \
-            --event-source arn:aws:sqs:us-east-1:125702582030:skeleton-pub-queue \
-            --region us-east-1 \
+            --event-source arn:aws:sqs:$AWS_REGION:$(aws sts get-caller-identity --query Account --output text):$QUEUE_NAME \
+            --region $AWS_REGION \
             --query 'EventSourceMappings[0].UUID' \
             --output text 2>/dev/null)
 
           if [ "$MAPPING_UUID" != "None" ] && [ -n "$MAPPING_UUID" ]; then
-            terraform import aws_lambda_event_source_mapping.from_sqs "$MAPPING_UUID"
+            terraform import aws_lambda_event_source_mapping.from_sqs "$MAPPING_UUID" || echo "Event Source Mapping already managed"
           else
             echo "Event Source Mapping not found"
           fi
-
         continue-on-error: true
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           TF_VAR_project_name: ${{ env.PROJECT_NAME }}
         working-directory: terraform
-  
+
       - name: Terraform Apply
-        run: |
-          terraform apply -auto-approve
+        run: terraform apply -auto-approve
         working-directory: terraform
         env:
           TF_VAR_project_name: ${{ env.PROJECT_NAME }}
